name = "EchelleCCFs"
uuid = "5d9f57b1-d7b5-417c-8d79-eedbcaad0187"
authors = ["Eric Ford"]
version = "0.2.9"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RvSpectMLBase = "c48404b2-35ea-40e7-ac7f-06a53de703d6"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ThreadedIterables = "11d239b0-c0b9-11e8-1935-d5cfa53abb03"

[compat]
CSV = "0.7, 0.8, 0.9.10, 0.9.11, 0.10"
DataFrames = "0.20, 0.21, 0.22, 1.0, 1.1"
FITSIO = "0.16, 0.17"
ForwardDiff = "0.10"
LsqFit = "0.13, 0.15"
NaNMath = "0.3, 1"
NamedTupleTools = "0.13, 0.14"
Optim = "1.2"
OrderedCollections = "1.3"
PDMats = "0.10, 0.11"
QuadGK = "2.4"
Query = "1"
RvSpectMLBase = "0.2"
SpecialFunctions = "1.0, 1.1, 2"
StaticArrays = "1"
Statistics = "1"
StatsBase = "0.33, 0.34"
ThreadedIterables = "0.2"
julia = "1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9"
